# This file describes the keymaps that will be built by the GitHub Actions CI.
# Most options are defined by CMake arguments, see definitions in keymaps/quacken.keymap.
# Each keymap is an "artifact", whose name goes as follows:
#
#   `quacken_[variant]_[layout]_[hold_taps]_[options]`
#
# - [variant]:
#   - flex (integrated rp2040 micro-controller)
#   - zero (promicro, you’ll have to update the `board` field to have your actual promicro board)
#
# - [layout]: (qwerty when omitted)
#   - `ergol`     (KB_LAYOUT_ERGOL)
#   - `azerty`    (KB_LAYOUT_AZERTY)
#   - `lafayette` (KB_LAYOUT_QWERTY_LAFAYETTE)
#   - ... probably more to come in the future
#
# - [hold_taps]: (hrm when omitted)
#   - `ez`  (HT_NONE): no hold-taps, VERY simple config (recommended for absolute beginners)
#   - `tt`  (HT_THUMB_TAPS): hold-taps on thumb keys (recommended for beginner/intermediate users)
#   - `hrm` (HT_HOME_ROW_MODS): homerow-mods enabled and refactored thumb keys (default)
#   - `2tk` (HT_TWO_THUMB_KEYS): hrm enabled and only two thumb keys used per thumb (needed if you use a rotary encoder)
#
# - [options]:
#   - `vim` (VIM_NAVIGATION): use two `VimNav` and `NumRow` layers instead of `NavNum`
#   - `left` (LEFT_HAND_SPACE): space on the left thumb, backspace on the right thumb
#   - `shift` (HRM_SHIFT): add shift as a pinky homerow-mod

include:
    # **** Quacken ****
    #
    # dummy firmware, just making sure we can build for the RP2040
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: tester_pro_micro
    artifact-name: quacken_test
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y

    # Quacken Zero + SparkFun RP2040, default config
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: quacken_zero
    artifact-name: quacken_zero
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y

    # Quacken Flex, default config
  - board: quacken_flex/rp2040
    artifact-name: quacken_flex
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y

    # Quacken Flex, Ergol + Vim + hrm_shift config
  - board: quacken_flex/rp2040
    artifact-name: quacken_flex_ergol_vim_shift
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHRM_SHIFT"
      -DCONFIG_ZMK_STUDIO=y

    # Quacken Flex, Ergol + Vim + 2tk config
  - board: quacken_flex/rp2040
    artifact-name: quacken_flex_ergol_2tk
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHT_TWO_THUMB_KEYS"
      -DCONFIG_ZMK_STUDIO=y

    # Quacken Flex, Azerty + thumb-taps config
  - board: quacken_flex/rp2040
    artifact-name: quacken_flex_azerty_tt
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_AZERTY;-DHT_THUMB_TAPS"
      -DCONFIG_ZMK_STUDIO=y

    # Quacken Flex, Ergol + Hummingbird config
  - board: quacken_flex/rp2040
    artifact-name: quacken_flex_ergol_hummingbird
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DHUMMINGBIRD"
      -DCONFIG_ZMK_STUDIO=y


    # **** Totem ****
    #
    # Default config
  - board: xiao_ble//zmk
    shield: totem_left
    artifact-name: totem_default_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble//zmk
    shield: totem_right
    artifact-name: totem_default_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y

    # Ergo-L + Vim + hrm_shift config
  - board: xiao_ble//zmk
    shield: totem_left
    artifact-name: totem_ergol_vim_shift_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHRM_SHIFT"
      -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble//zmk
    shield: totem_right
    artifact-name: totem_ergol_vim_shift_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHRM_SHIFT"
      -DCONFIG_ZMK_STUDIO=y

    # Ergo-L + Vim + 2tk config
  - board: xiao_ble//zmk
    shield: totem_left
    artifact-name: totem_ergol_2tk_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHT_TWO_THUMB_KEYS"
      -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble//zmk
    shield: totem_right
    artifact-name: totem_ergol_2tk_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHT_TWO_THUMB_KEYS"
      -DCONFIG_ZMK_STUDIO=y

    # Azerty + thumb-taps config
  - board: xiao_ble//zmk
    shield: totem_left
    artifact-name: totem_azerty_tt_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_AZERTY;-DHT_THUMB_TAPS"
      -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble//zmk
    shield: totem_right
    artifact-name: totem_azerty_tt_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_AZERTY;-DHT_THUMB_TAPS"
      -DCONFIG_ZMK_STUDIO=y

    # Ergo-L + Hummingbird config
  - board: xiao_ble//zmk
    shield: totem_left
    artifact-name: totem_ergol_hummingbird_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DHUMMINGBIRD"
      -DCONFIG_ZMK_STUDIO=y
  - board: xiao_ble//zmk
    shield: totem_right
    artifact-name: totem_ergol_hummingbird_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DHUMMINGBIRD"
      -DCONFIG_ZMK_STUDIO=y


    # **** Corne ****
    #
    # Default config
  - board: nice_nano@2//zmk
    shield: corne_left
    artifact-name: corne_default_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano@2//zmk
    shield: corne_right
    artifact-name: corne_default_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y

    # Ergo-L + Vim + hrm_shift config
  - board: nice_nano@2//zmk
    shield: corne_left
    artifact-name: corne_ergol_vim_shift_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHRM_SHIFT"
      -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano@2//zmk
    shield: corne_right
    artifact-name: corne_ergol_vim_shift_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHRM_SHIFT"
      -DCONFIG_ZMK_STUDIO=y

    # Ergo-L + Vim + 2tk config
  - board: nice_nano@2//zmk
    shield: corne_left
    artifact-name: corne_ergol_2tk_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHT_TWO_THUMB_KEYS"
      -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano@2//zmk
    shield: corne_right
    artifact-name: corne_ergol_2tk_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHT_TWO_THUMB_KEYS"
      -DCONFIG_ZMK_STUDIO=y

    # Azerty + thumb-taps config
  - board: nice_nano@2//zmk
    shield: corne_left
    artifact-name: corne_azerty_tt_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_AZERTY;-DHT_THUMB_TAPS"
      -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano@2//zmk
    shield: corne_right
    artifact-name: corne_azerty_tt_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_AZERTY;-DHT_THUMB_TAPS"
      -DCONFIG_ZMK_STUDIO=y

    # Ergo-L + Hummingbird config
  - board: nice_nano@2//zmk
    shield: corne_left
    artifact-name: corne_ergol_hummingbird_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DHUMMINGBIRD"
      -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano@2//zmk
    shield: corne_right
    artifact-name: corne_ergol_hummingbird_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DHUMMINGBIRD"
      -DCONFIG_ZMK_STUDIO=y


    # **** Ferris ****
    #
    # Note: not enough memory for ZMK Studio or USB logging
    # default config
  - board: ferris//zmk
    artifact-name: ferris

    # Ergo-L + Vim
  - board: ferris//zmk
    artifact-name: ferris_ergol_vim
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION"


    # **** Sweep / Hypergolic / Cradio ****
    #
    # Note: Cradio is a firmware for a few 34 key keyboards,
    # including Cradio, Hypergolic and Sweep.
    # As the Sweep in the most famous keeb in the list,
    # the artifact is named after it.
    #
    # default config
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: cradio_left
    artifact-name: sweep_pro_micro_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
  - board: sparkfun_pro_micro_rp2040//zmk
    shield: cradio_right
    artifact-name: sweep_pro_micro_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y


    # **** Glove80 ****
    #
    # Default config
  - board: glove80_lh
    artifact-name: glove80_default_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y
  - board: glove80_rh
    artifact-name: glove80_default_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DCONFIG_ZMK_STUDIO=y

    # Ergo-L + Vim + hrm_shift config
  - board: glove80_lh
    artifact-name: glove80_ergol_vim_shift_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHRM_SHIFT"
      -DCONFIG_ZMK_STUDIO=y
  - board: glove80_rh
    artifact-name: glove80_ergol_vim_shift_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHRM_SHIFT"
      -DCONFIG_ZMK_STUDIO=y

    # Ergo-L + Vim + 2tk config
  - board: glove80_lh
    artifact-name: glove80_ergol_2tk_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHT_TWO_THUMB_KEYS"
      -DCONFIG_ZMK_STUDIO=y
  - board: glove80_rh
    artifact-name: glove80_ergol_2tk_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DVIM_NAVIGATION;-DHT_TWO_THUMB_KEYS"
      -DCONFIG_ZMK_STUDIO=y

    # Azerty + thumb-taps config
  - board: glove80_lh
    artifact-name: glove80_azerty_tt_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_AZERTY;-DHT_THUMB_TAPS"
      -DCONFIG_ZMK_STUDIO=y
  - board: glove80_rh
    artifact-name: glove80_azerty_tt_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_AZERTY;-DHT_THUMB_TAPS"
      -DCONFIG_ZMK_STUDIO=y

    # Ergo-L + Hummingbird config
  - board: glove80_lh
    artifact-name: glove80_ergol_hummingbird_left
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DHUMMINGBIRD"
      -DCONFIG_ZMK_STUDIO=y
  - board: glove80_rh
    artifact-name: glove80_ergol_hummingbird_right
    snippet: studio-rpc-usb-uart
    cmake-args: >
      -DDTS_EXTRA_CPPFLAGS="-DKB_LAYOUT_ERGOL;-DHUMMINGBIRD"
      -DCONFIG_ZMK_STUDIO=y
